# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  dispatch:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        # A repo scoped GitHub Personal Access Token
        token: ${{ secrets.REPO_PUBLISH_TOKEN}}
        # The full name of the repository to send the dispatch.
        repository: 'CodeLinaro/hexagon-builder'
        # A custom webhook event name.
        event-type: repo-released
        # JSON payload with extra information about the webhook event that your action or worklow may use.
        client-payload: '{"repo_name": "${{ github.repository }}", "tag_name": "${{ github.event.release.tag_name }}", "ref": "${{ github.ref }}"}'
